ALTER TABLE CUSTOMER
ADD INDEX `c_mktsegment_idx` USING HASH (`C_MKTSEGMENT` ASC) ;

ALTER TABLE ORDERS 
ADD INDEX `o_orderdate_idx` USING BTREE (`O_ORDERDATE` ASC) ;

ALTER TABLE LINEITEM
ADD INDEX `l_shipdate_idx` USING BTREE (`L_SHIPDATE` ASC) ;
